In [12]:
import gym
import numpy as np

In [19]:
env = gym.make('FrozenLake-v0')
np.set_printoptions(precision=3)

In [20]:


#> Discrete(2)
print(env.observation_space)

for i in range(100):
    env.reset()
    obs=r=done=info=None
    while done!=True:
        env.render()
        obs,r,done,info = env.step(env.action_space.sample())
        
    print(f'obs={obs},r={r},done={done},i={info}')
    
env.close()

Discrete(16)

SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
obs=5,r=0.0,done=True,i={'prob': 0.3333333333333333}

SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
obs=5,r=0.0,done=True,i={'prob': 0.3333333333333333}

SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
obs=15,r=1.0,done=True,i={'prob': 0.3333333333333333}

SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
obs

In [21]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [31]:
for i in range(100):
    env.reset()
    obs=r=done=info=None
    while done!=True:
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        obs,r,done,info = env.step(a)
        if r==1:
            env.render()
    print(f'obs={obs},r={r},done={done},i={info}')
    
env.close()

obs=7,r=0.0,done=True,i={'prob': 0.3333333333333333}
obs=12,r=0.0,done=True,i={'prob': 0.3333333333333333}
obs=7,r=0.0,done=True,i={'prob': 0.3333333333333333}
obs=5,r=0.0,done=True,i={'prob': 0.3333333333333333}
obs=7,r=0.0,done=True,i={'prob': 0.3333333333333333}
obs=5,r=0.0,done=True,i={'prob': 0.3333333333333333}
obs=12,r=0.0,done=True,i={'prob': 0.3333333333333333}
obs=5,r=0.0,done=True,i={'prob': 0.3333333333333333}
obs=5,r=0.0,done=True,i={'prob': 0.3333333333333333}
obs=5,r=0.0,done=True,i={'prob': 0.3333333333333333}
obs=5,r=0.0,done=True,i={'prob': 0.3333333333333333}
obs=7,r=0.0,done=True,i={'prob': 0.3333333333333333}
obs=5,r=0.0,done=True,i={'prob': 0.3333333333333333}
obs=7,r=0.0,done=True,i={'prob': 0.3333333333333333}
obs=5,r=0.0,done=True,i={'prob': 0.3333333333333333}
obs=5,r=0.0,done=True,i={'prob': 0.3333333333333333}
obs=5,r=0.0,done=True,i={'prob': 0.3333333333333333}
obs=12,r=0.0,done=True,i={'prob': 0.3333333333333333}
obs=5,r=0.0,done=True,i={'prob': 0.33333333

In [22]:
print("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.4815


In [23]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[1.672e-01 3.382e-03 2.265e-03 4.427e-03]
 [9.002e-05 1.999e-03 3.504e-04 6.689e-02]
 [6.254e-04 1.430e-04 3.205e-03 1.172e-01]
 [6.107e-05 3.022e-04 5.683e-05 7.444e-02]
 [2.837e-01 0.000e+00 1.043e-04 1.536e-03]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [3.209e-05 1.002e-04 2.425e-02 2.555e-09]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 2.890e-03 2.038e-04 5.095e-01]
 [1.176e-04 5.944e-01 0.000e+00 0.000e+00]
 [2.165e-01 7.404e-05 1.023e-03 2.650e-04]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [4.109e-03 4.324e-03 7.167e-01 2.653e-03]
 [0.000e+00 0.000e+00 0.000e+00 9.555e-01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00]]
