In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from IPython.display import clear_output, display, Math, Latex
from atlas_ml import *
import random, math

In [4]:
def F(X):
    fitness = -(X[0]-1)**2 - (X[0]-X[1])**2 - (X[0]-X[1]-X[2]-2)**2
    return fitness

In [5]:
GO = genetic_optimizer(6,3,F)

In [6]:
np.random.uniform(size=5) < 0.5 

array([False,  True, False,  True, False])

In [13]:
GO.optimize()

-5.844837961006094e-08
[1.00022505 1.00022505 1.00022505 1.00022505 1.76147406 1.00022505]
-5.844837961006094e-08
[1.00022505 1.00022505 1.00022505 1.00022505 1.00022505 1.00022505]
-5.844837961006094e-08
[1.00022505 1.00022505 1.00022505 1.00022505 1.00022505 1.00022505]
-5.844837961006094e-08
[1.00022505 1.00022505 1.00022505 1.00022505 1.00022505 0.35751935]
-5.844837961006094e-08
[1.00022505 1.00022505 1.00022505 1.00022505 1.00022505 1.00022505]
-5.844837961006094e-08
[1.00022505 1.00022505 1.00022505 1.00022505 1.00022505 0.78249396]
-5.844837961006094e-08
[1.00022505 1.00022505 1.00022505 1.00022505 1.00022505 1.00022505]
-5.844837961006094e-08
[1.00022505 1.00022505 1.00022505 1.1223639  1.1223639  1.1223639 ]
-5.844837961006094e-08
[1.00022505 1.00022505 1.00022505 1.00022505 1.00022505 1.00022505]
-5.844837961006094e-08
[1.00022505 1.00022505 1.00022505 1.00022505 1.45493361 1.90108477]


(-5.844837961006094e-08, array([ 1.00022505,  1.00026484, -1.99996093]))