In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from IPython.display import clear_output, display, Math, Latex
import atlas_ml
import random, math

In [5]:
def F(X):
    fitness = -(X[0]-1)**2 - (X[0]-X[1])**2 - (X[0]-X[1]-X[2]-2)**2
    return fitness

In [6]:
GO = atlas_ml.genetic_optimizer(6,3,F)

In [7]:
np.random.uniform(size=5) < 0.5 

array([False,  True, False, False,  True])

In [8]:
GO.optimize()

-1.2196826949512019
[ 0.00969371  2.81569484  1.23935342 -1.89272283  3.66495225 -3.96604688]
-0.0001965150871769649
[0.99535099 0.99535099 0.99535099 0.99535099 0.99535099 0.99535099]
-0.00018110920171791916
[0.99347299 0.99347299 0.99347299 0.55067745 0.99347299 0.99347299]
-2.340207576620965e-05
[ 0.99646487  0.99646487  0.99646487  0.99646487  0.45304194 -0.00312177]
-1.6847328112280997e-05
[0.99646487 0.99646487 0.99646487 0.99646487 0.99646487 0.18226155]
-1.328595890946747e-05
[0.99646487 0.99646487 0.99646487 1.0529786  0.99646487 0.99646487]
-1.328595890946747e-05
[0.99646487 0.99646487 0.99646487 0.99646487 0.99646487 0.99646487]
-1.2855118868779686e-05
[0.99646487 0.99646487 0.28368416 0.3511768  0.3511768  0.13413457]
-1.2855118868779686e-05
[0.99646487 0.99646487 0.99215845 0.99646487 1.05257353 1.90552921]
-1.2855118868779686e-05
[0.99646487 0.99646487 0.99646487 0.99646487 0.99646487 0.99646487]


(-1.0270341697347471e-05, array([ 0.99832972,  0.99686494, -2.00084496]))